sentry:
  dsn: "{SENTRY_DSN}"
  release:
    name: "{SENTRY_RELEASE_NAME}"
# This one is optional ... only if you want to use ai-story command
openAi:
  token: ...
amqp:
  url: "{AMQP_URL}"
discord:
    token: "MTAwMzI1NDA1ODQzOTY4NDA5Ng.GZfD18.jiZPfXvjYxZRJI_hSk2vGlrdzd7WI42zBun_Jo"
deploy:
  port: "{PORT}"
mongo:
  uri: "${MONGO_URI}"
